id: P001785
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W26445
  title: རྭ་སྟོད་བསྡུས་གྲྭ
  author: ''
  volumes:
    34323c03f52c4eebaa94faaeaa9f34a1:
      image_group_id: I1CZ2189
      title: ''
      volume_number: 1
      total_pages: 440
      base_file: v001.txt
