id: I250958BE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T18:24:18+00:00'
last_modified: '2022-06-07T15:08:35.420989+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26445
  title: རྭ་སྟོད་བསྡུས་གྲྭ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EA79:
      image_group_id: I1CZ2189
      title: ''
      total_pages: 440
      order: 1
      base_file: EA79.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
